title: Zebracorn Short Link Repo
description: Zebracorn Short Link Repo
logo: /assets/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from
  
collections:
  urls:
    output: true
    permalink: /:slug

#repository: hlaueriksson/jekyll-url-shortener
